#!/bin/bash
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Notepad++","body":"I hate reading other peoples code.\nSo I wrote mine, made it as open source project, and see others suffer.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Notepad++ #2","body":"Good programmers use Notepad++ to code.\nExtreme programmers use MS Word to code, in Comic Sans, center aligned.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Richard Stallman?","body":"If Im the Father of Open Source, it was conceived through artificial insemination using stolen sperm without my knowledge or consent.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Martin Golding","body":"Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "L. Peter Deutsch","body":"To iterate is human, to recurse divine.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Seymour Cray","body":"The trouble with programmers is that you can never tell what a programmer is doing until its too late.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Brian Kernighan","body":"Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Alan Kay","body":"Most software today is very much like an Egyptian pyramid with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Bill Gates","body":"Measuring programming progress by lines of code is like measuring aircraft building progress by weight.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Christopher Thompson","body":"Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Mondays code.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Vidiu Platon","body":"I dont care if it works on your machine! We are not shipping your machine!","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Edward V Berard","body":"Walking on water and developing software from a specification are easy if both are frozen.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "pixadel","body":"Fine, Java MIGHT be a good example of what a programming language should be like. But Java applications are good examples of what applications SHOULDNT be like.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Oktal","body":"I think Microsoft named .Net so it wouldnt show up in a Unix directory listing.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Bjarne Stroustrup","body":"In C++ its harder to shoot yourself in the foot, but when you do, you blow off your whole leg.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Moshers Law of Software Engineering","body":"Dont worry if it doesnt work right. If everything did, youd be out of a job.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Bob Gray","body":"Writing in C or C++ is like running a chain saw with all the safety guards removed.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Roberto Waltman","body":"In the one and only true way. The object-oriented version of \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Gavin Russell Baker","body":"C++ : Where friends have access to your private members.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Linus Torvalds","body":"Software is like sex: Its better when its free.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Cult of vi","body":"Emacs is a great operating system, lacking only a decent editor.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Church of Emacs","body":"vi has two modes - \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Steve Jobs","body":"Picasso had a saying: \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "brotips #1001","body":"Do everything for greatness, not money. Money follows greatness.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Robin Williams","body":"God gave men both a penis and a brain, but unfortunately not enough blood supply to run both at the same time.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Darth Vader","body":"You dont get to 500 million star systems without making a few enemies.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Doug Linder","body":"A good programmer is someone who always looks both ways before crossing a one-way street.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Jean-Claude van Damme","body":"A cookie has no soul, its just a cookie. But before it was milk and eggs.\nAnd in eggs theres the potential for life.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Michael Feldman","body":"Java is, in many ways, C++--.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Don Ho","body":"Je mange donc je chie.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Don Ho #2","body":"RTFM is the true path of every developer.\nBut it would happen only if theres no way out.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Don Ho #3","body":"Smartphone is the best invention of 21st century for avoiding the eyes contact while crossing people you know on the street.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #1","body":"An opinion without 3.14 is just an onion.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #2","body":"Before sex, you help each other get naked, after sex you only dress yourself.\nMoral of the story: in life no one helps you once youre fucked.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #3","body":"Im not totally useless. I can be used as a bad example.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #4","body":"Life is too short to remove USB safely.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #5","body":"\","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #6","body":"Going to Mc Donalds for a salad is like going to a whore for a hug.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #7","body":"I need a six month holiday, TWICE A YEAR!","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #8","body":"Everything is a knife if youre strong enough.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #9","body":"I just read a list of \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #10","body":"Roses are red,\nViolets are red,\nTulips are red,\nBushes are red,\nTrees are red,\nHOLY SHIT MY\nGARDENS ON FIRE!!","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #11","body":"We stopped checking for monsters under our bed, when we realized they were inside us.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #12","body":"I would rather check my facebook than face my checkbook.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #13","body":"Whoever says Paper beats Rock is an idiot. Next time I see someone say that I will throw a rock at them while they hold up a sheet of paper.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #14","body":"A better world is where chickens can cross the road without having their motives questioned.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #15","body":"If I didnt drink, how would my friends know I love them at 2 AM?","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #16","body":"Q: How do you generate a random string?\nA: Put a Windows user in front of vi, and tell him to exit.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #17","body":"All you need is love,\nall you want is sex,\nall you have is porn.\n","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #18","body":"Never get into fights with ugly people, they have nothing to lose.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #19","body":"F_CK: All I need is U.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #20","body":"Never make eye contact while eating a banana.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #21","body":"I love my sixpack so much, I protect it with a layer of fat.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #22","body":"\","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #23","body":"Everybody talks about leaving a better planet for the children.\nWhy nobody tries to leave better children to the planet?","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #24","body":"An Architects dream is an Engineers nightmare.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #25","body":"In a way, I feel sorry for the kids of this generation.\nTheyll have parents who know how to check browser history.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #26","body":"I would never bungee jump.\nI came into this world because of a broken rubber, and Im not going out cause of one.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #27","body":"I dont have a problem with caffeine.\nI have a problem without caffeine.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #28","body":"Why 6 afraid of 7?\nBecause 7 8 9 (seven ate nine) while 6 and 9 were flirting.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #30","body":"Why do Java developers wear glasses?\nBecause they dont C#.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #31","body":"A babys laughter is one of the most beautiful sounds you will ever hear. Unless its 3 AM. And youre home alone. And you dont have a baby.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #32","body":"Two bytes meet. The first byte asks, \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #33","body":"Programmer - an organism that turns coffee into software.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #34","body":"Its not a bug - its an undocumented feature.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #35","body":"Should array index start at 0 or 1?\nMy compromised solution is 0.5","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #36","body":"Every single time when Im about to hug someone extremely sexy, I hit the mirror.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #37","body":"My software never has bugs. It just develops random features.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #38","body":"LISP = Lots of Irritating Silly Parentheses.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #39","body":"Perl, the only language that looks the same before and after RSA encryption.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #40","body":"People ask me why, as an atheist, I still say: OH MY GOD.\nIt makes perfect sense: We say \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #41","body":"1. Dig a hole.\n2. Name it love.\n3. Watch people falling in love.\n","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #42","body":"Dont think of yourself as an ugly person.\nThink of yourself as a beautiful monkey.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #43","body":"Afraid to die alone?\nBecome a bus driver.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #44","body":"The first 5 days after the weekend are always the hardest.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #45","body":"Rhinos are just fat unicorns.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #46","body":"Sometimes when Im writing Javascript I want to throw up my hands and say \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #47","body":"Kids are like farts.\nYou can only stand yours.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #48","body":"If you were born in Israel, youd probably be Jewish.\nIf you were born in Saudi Arabia, youd probably be Muslim.\nIf you were born in India, youd probably be Hindu.\nBut because you were born in North America, youre Christian.\nYour faith is not inspired by some divine, constant truth.\nIts simply geography.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #49","body":"There are 2 types of people in this world:\nPeople who say they pee in the shower, and the dirty fucking liars.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #50","body":"London 2012 Olympic Games - A bunch of countries coming across the ocean to put their flags in britain and try to get a bunch of gold... its like history but opposite.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #51","body":"I dont need a stable relationship,\nI just need a stable Internet connection.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #52","body":"Whats the difference between religion and bullshit?\nThe bull.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #53","body":"Today, as I was waiting for my girlfriend in the street, I saw a woman who looked a lot like her. I ran towards her, my arms in the air ready to give her a hug, only to realise it wasnt her. I then had to pass the woman, my arms in the air, still running. FML","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #54","body":"Today, I finally got my hands on the new iPhone 5, after I pulled it out of a patients rectum. FML","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #55","body":"Violent video games wont change our behaviour.\nIf people were influenced by video games, then the majority of Facebook users would be farmers right now.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #56","body":"Religion is like circumcision.\nIf you wait until someone is 21 to tell them about it they probably wont be interested.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #57","body":"No, no, no, Im not insulting you.\nIm describing you.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #58","body":"I bought a dog once. Named him \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #60","body":"Yesterday I named my Wifi network \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #61","body":"Your mother is so fat,\nthe recursive function computing her mass causes a stack overflow.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #62","body":"Oral sex makes my day, but anal sex makes my hole weak.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #63","body":"Im not saying I am Batman, I am just saying no one has ever seen me and Batman in the same room together.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #64","body":"I took a taxi today.\nThe driver told me \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #65","body":"A man without God is like a fish without a bicycle.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #66","body":"I hate how spiders just sit there on the walls and act like they pay rent!","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #67","body":"Whenever someone starts a sentence by saying \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #68","body":"Im not laughing at you, Im laughing with you, youre just not laughing.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #69","body":"Women need a reason to have sex. Men just need a place.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #70","body":"If abortion is murder then are condoms kidnapping?","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #71","body":"Men also have feelings.\nFor example, they can feel hungry.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #72","body":"Project Manager:\nA person who thinks 9 women can deliver a baby in 1 month.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #73","body":"If you try and dont succeed, cheat. Repeat until caught. Then lie.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #74","body":"Olympics is the stupidest thing.\nPeople are so proud to be competing for their country.\nThey play their stupid song and raise some dumb flags.\nId love to see no flags raised, no song, no mention of country.\nOnly people.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #75","body":"I think therefore I am\nnot religious.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #76","body":"Even if being gay were a choice, so what?\nPeople choose to be assholes and they can get married.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #77","body":"Governments are like diapers.\nThey should be changed often, and for the same reason.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #78","body":"If you expect the world to be fair with you because you are fair, youre fooling yourself.\nThats like expecting the lion not to eat you because you didnt eat him.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #79","body":"Im a creationist.\nI believe man create God.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #80","body":"Lets eat kids.\nLets eat, kids.\n\nUse a comma.\nSave lives.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #81","body":"A male engineering student was crossing a road one day when a frog called out to him and said, \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #82","body":"Programmers never die.\nThey just go offline.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #83","body":"Copy from one, its plagiarism.\nCopy from two, its research.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #84","body":"Saying that Java is nice because it works on all OSes is like saying that anal sex is nice because it works on all genders.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #85","body":"Race, religion, ethnic pride and nationalism etc... does nothing but teach you how to hate people that youve never met.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #86","body":"Farts are just the ghosts of the things we eat.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #87","body":"I promised I would never kill someone who had my blood.\nBut that mosquito made me break my word.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #88","body":"","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #89","body":"Im drunk and youre still ugly.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #90","body":"Clapping:\n(verb)\nRepeatedly high-fiving yourself for someone elses accomplishments.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #91","body":"CV: ctrl-C, ctrl-V","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #92","body":"Mondays are not so bad.\nIts your job that sucks.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #93","body":"[In a job interview]\nInterviewer: Whats your greatest weakness?\nCandidate: Honesty.\nInterviewer: I dont think honesty is a weakness.\nCandidate: I dont give a fuck what you think.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #94","body":"Hey, I just met you\nAnd this is crazy\nHeres my number 127.0.0.1\nPing me maybe?","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #95","body":"YES!\nIm a programmer, and\nNO!\nIt doesnt mean that I have to fix your PC!","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #96","body":"Code for 6 minutes, debug for 6 hours.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #97","body":"Real Programmers dont comment their code.\nIf it was hard to write, it should be hard to read.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #98","body":"My neighbours listen to good music.\nWhether they like it or not.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #99","body":"Ive been using Vim for about 2 years now,\nmostly because I cant figure out how to exit it.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #100","body":"Dear YouTube,\nI can deal with Ads.\nI can deal with Buffer.\nBut when Ads buffer, I suffer.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #101","body":"Its always sad when a man and his dick share only one brain...\nand it turns out to be the dicks.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #102","body":"If IE is brave enough to ask you to set it as your default browser,\ndont tell me you dare not ask a girl out.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #103","body":"Turn on your brain, turn off TV.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #104","body":"The main idea of \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #105","body":"","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #106","body":"When I die, I want to go peacefully like my grandfather did, in his sleep\n- not screaming, like the passengers in his car.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #107","body":"Remember, YOUR God is real.\nAll those other Gods are ridiculous, made-up nonsense.\nBut not yours.\nYour God is real. Whichever one that is.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #108","body":"I hope Bruce Willis dies of a Viagra overdose,\nThe way you can see the headline:\nBruce Willis, Died Hard","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #109","body":"","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #110","body":"A programmer had a problem, so he decided to use threads.\nNow 2 has. He problems.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #111","body":"I love how the internet has improved peoples grammar far more than any English teacher has.\nIf you write \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #112","body":"#hulk {\n height: 200%;\n width: 200%;\n color: green;\n}","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #113","body":"Open source is communism.\nAt least it is what communism was meant to be.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #114","body":"How can you face your problem if your problem is your face?","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #115","body":"YOLOLO:\nYou Only LOL Once.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #116","body":"Every exit is an entrance to new experiences.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #117","body":"A Native American was asked:\n\","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #118","body":"I love necrophilia, but i cant stand the awkward silences.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #119","body":"\","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #120","body":"Life is what happens to you while youre looking at your smartphone.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #121","body":"Thing to do today:\n1. Get up\n2. Go back to bed","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #122","body":"Nerd?\nI prefer the term \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #123","body":"How can you face your problem if your problem is your face?","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #124","body":"You dont need religion to have morals.\nIf you cant determine right from wrong then you lack empathy, not religion.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #125","body":"Pooping with the door opened is the meaning of true freedom.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #126","body":"Social media does not make people stupid.\nIt just makes stupid people more visible.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #127","body":"Dont give up your dreams.\nKeep sleeping.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #128","body":"I love sleep.\nNot because Im lazy.\nBut because my dreams are better than my real life.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #129","body":"","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #130","body":"Common sense is so rare, its kinda like a superpower...","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #131","body":"The best thing about a boolean is even if you are wrong, you are only off by a bit.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #132","body":"Benchmarks dont lie, but liars do benchmarks.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #133","body":"Multitasking: Screwing up several things at once.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #134","body":"Linux is user friendly.\nIts just picky about its friends.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #135","body":"Theory is when you know something, but it doesnt work.\nPractice is when something works, but you dont know why.\nProgrammers combine theory and practice: nothing works and they dont know why.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #136","body":"Documentation is like sex:\nwhen its good, its very, very good;\nwhen its bad, its better than nothing.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #137","body":"Home is where you poop most comfortably.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #138","body":"Laptop Speakers problem: too quiet for music, too loud for porn.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #139","body":"Chinese food to go: $16\nGas to go get the food: $2\nDrove home just to realize they forgot one of your containers: RICELESS","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #140","body":"MS Windows is like religion to most people: they are born into it, accept it as default, never consider switching to another.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #141","body":"To most religious people, the holy books are like a software license (EULA).\nNobody actually reads it. They just scroll to the bottom and click \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #142","body":"You are nothing but a number of days,\nwhenever each day passes then part of you has gone.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #143","body":"If 666 is evil, does that make 25.8069758011 the root of all evil?","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #144","body":"I dont want to sound like a badass but...\nI eject my USB drive without removing it safely.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #145","body":"feet (noun)\na device used for finding legos in the dark","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #146","body":"Buy a sheep\nName it \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #147","body":"I dig, you dig, we dig,\nhe dig, she dig, they dig...\n\nIts not a beautiful poem,\nbut its very deep.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #148","body":"UNIX command line Russian roulette:\n[ $[ $RANDOM % 6 ] == 0 ] && rm -rf /* || echo *Click*","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #149","body":"unzip, strip, top, less, touch, finger, grep, mount, fsck, more, yes, fsck, fsck, fsck, umount, sleep.\n\nNo, its not porn. Its Unix.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #150","body":"To understand what recursion is, you must first understand recursion.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #151","body":"Q: Whats the object-oriented way to become wealthy?\nA: Inheritance.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #152","body":"A SQL query goes into a bar, walks up to two tables and asks, \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #153","body":"You are not fat, you are just more visible.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Anonymous #154","body":"Minimalist\n (. .)\n ) (\n ( Y )\nASCII Art","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Internet #1","body":"If you spell \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Louis C.K.","body":"Im a good citizen. Im a good father. I recycle and I masturbate.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Mary Oliver","body":"Someone I loved once gave me a box full of darkness.\nIt took me years to understand that this, too, was a gift.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Floor","body":"If you fall, I will be there.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Simon Amstell","body":"If you have some problem in your life and need to deal with it, then use religion, thats fine.\nI use Google.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "James Bond","body":"James, James Bond.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Albert Einstein","body":"Only 3 things are infinite:\n1. Universe.\n2. Human Stupidity.\n3. Winrars free trial.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Terry Pratchett","body":"Artificial Intelligence is no match for natural stupidity.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Stewart Brand","body":"Once a new technology starts rolling, if youre not part of the steamroller,\nyoure part of the road.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Sam Redwine","body":"Software and cathedrals are much the same - first we build them, then we pray.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Jan L. A. van de Snepscheut","body":"In theory, there is no difference between theory and practice. But, in practice, there is.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Jessica Gaston","body":"One mans crappy software is another mans full time job.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Barack Obama","body":"Yes, we scan!","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "George W. Bush","body":"Where is my Nobel prize?\nI bombed people too.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Gandhi","body":"Earth provides enough to satisfy every mans need, but not every mans greed.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "R. D. Laing","body":"Life is a sexually transmitted disease and the mortality rate is one hundred percent.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Apple fan boy","body":"Ill buy a second iPhone 5 and buy a lot of iOS applications so that Apple will be able to buy Samsung (this shitty company)\nto shut it down and all the Apple haters will be forced to have an iPhone. Muhahaha...","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Hustle Man","body":"Politicians are like sperm.\nOne in a million turn out to be an actual human being.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Mark Twain","body":"Censorship is telling a man he cant have a steak just because a baby cant chew it.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Friedrich Nietzsche","body":"There is not enough love and goodness in the world to permit giving any of it away to imaginary beings.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Dhalsim","body":"Pain is a state of mind and I dont mind your pain.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Elie Wiesel","body":"Human beings can be beautiful or more beautiful,\nthey can be fat or skinny, they can be right or wrong,\nbut illegal? How can a human being be illegal?","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Dennis Ritchie","body":"Empty your memory, with a free(), like a pointer.\nIf you cast a pointer to a integer, it becomes the integer.\nIf you cast a pointer to a struct, it becomes the struct.\nThe pointer can crash, and can overflow.\nBe a pointer my friend.","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "Chewbacca","body":"Uuuuuuuuuur Ahhhhrrrrrr\nUhrrrr Ahhhhrrrrrr\nAaaarhg...","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues
curl --user "reivax-boucoi:MYSECRETPASSWORD" -X POST --data '{"title": "#JeSuisCharlie","body":"Freedom of expression is like the air we breathe, we dont feel it, until people take it away from us.\n\nFor this reason, Je suis Charlie, not because I endorse everything they published, but because I cherish the right to speak out freely without risk even when it offends others.\nAnd no, you cannot just take someones life for whatever he/she expressed.\n\nHence this \","labels":["bug"]}' https://api.github.com/repos/albangossard/Indoor-Farming-Bot/issues

